[package]
name = "qrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qip = "1.4.0"
crossterm = "0.27.0"
ratatui = "0.23.0"